### ISSUE TITLE
Replace regexp by XML parsing ?

### ISSUE THREAD

**Issue by lasconic** [bust4cap/epub2cbz#1]
I tried to convert a couple epub on macosx. The program is slow or locked while evaluating [this large regexp](https://github.com/bust4cap/epub2cbz/blob/930bddc6ba35224545f6789c3736311cd5257cfd/epub2cbz.py#L303). 

Maybe parsing the XML would be easier to read and more robust ?

**Comment by bust4cap** [comment]
sorry for the late (what an understatement, lol) response. seems like you fixed it yourself in your own fork already^^
[](https://github.com/lasconic/epub2cbz)
