### ISSUE TITLE
Error creating blank image

### ISSUE THREAD

**Issue by laffitto** [bust4cap/epub2cbz#1]
When I run the program, it shows the following. I'm not sure if there is a problem with the format of the comics. All epub files are downloaded from [link removed]. I have a lot of comics downloaded from it and hope it works.
This is an example of a comic book. I compressed it to make it easier to upload to github.

[link removed]
![image](https://github.com/user-attachments/assets/aa80f8f6-52e4-479a-b271-c03a9257f4da)

**Comment by bust4cap** [comment]
thank you for your report. i will look into it right away :)

**Comment by bust4cap** [comment]
@laffitto newest release v2024.12.27-1 should fix this.
please report back if you still have issues
